name: Build, test, zip and deploy for node projects

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
# fill in node version
env: 
  node_version: 16

jobs: 
  build-test-zip: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}

    - name: "Build"
      run: | 
        npm ci

    - name: "Test"
      run: | 
        echo Run tests
        
    - name: "Package app.zip"
      run: | 
        zip -r app.zip . -x .git/\*

    - uses: actions/upload-artifact@master
      if: ${{ !env.ACT }}
      with:
        path: app.zip
        name: app

  deploy-dev: 
    # fill in dev branch
    if: ${{ (github.head_ref || github.ref_name) == 'develop' }}
    uses: aimsinnovation/public-workflows/.github/workflows/zip-deploy.yml@master
    needs: build-test-zip
    secrets: inherit
    with: 
      # change APP_DEV_NAME to dev app name
      scm_url: ${{ format('https://{0}.scm.azurewebsites.net/api/zipdeploy', 'APP_DEV_NAME') }}
      artifact_name: app

  deploy-staging: 
    # fill in staging branch
    if: ${{ (github.head_ref || github.ref_name) == 'master' }}
    uses: aimsinnovation/public-workflows/.github/workflows/zip-deploy.yml@master
    needs: build-test-zip
    secrets: inherit
    with: 
      # change APP_STAGING to staging app name
      scm_url: ${{ format('https://{0}.scm.azurewebsites.net/api/zipdeploy', 'APP_STAGING_NAME') }}
      artifact_name: app